// Generated by create-react-app 
// @last update on Dec 4, 2021

import React from 'react';
import TimelinePortfolio from "./components/TimelinePortfolioComponent";
import * as timelineData from "./data.json";
import CONST from './util';

function App() {

    return ( 
        <div className="main-canvas">
            <div className="hero-container"></div>
            <div className="portfolio-container">
                {initTimeline()}
            </div> 
            <div className="footer-container"></div>
        </div>
    );
}

function initTimeline() {

    const timelineTopTime       = Date.now();
    const timelineBottomTime    = new Date(2018, 1, 1);
    const projDataArr           = timelineData.projects;
    const expDataArr            = timelineData.experience;

    let data = [
        {
            termdate: 22,
            initdate: 45
        }, 
        {
            termdate: 14,
            initdate: 50
        },
        {
            termdate: 244,
            initdate: 455
        },
        {
            termdate: 323,
            initdate: 377
        }
    ]
    
    const timelineLength = (timelineTopTime - timelineBottomTime)/1000/60/60/24*CONST.DATE_TO_PIXEL_MULTIPLIER;
    return (
        <TimelinePortfolio 
            length={timelineLength}
            data={data}
        />
    );
}

export default App;
