// Generated by create-react-app 
// @last update on Dec 4, 2021

import React from 'react';
import TimelinePortfolio from "./components/TimelinePortfolioComponent";

function App() {
    return ( 
        <div className="main-canvas">
            <div className="hero-container"></div>
            <div className="portfolio-container">
                <TimelinePortfolio /> 
            </div> 
            <div className="footer-container"></div>
        </div>
    );
}

export default App;
