// Partly generated by create-react-app, also @author Quinn Tao
// @last update on Dec 14, 2021

import React from 'react';
import TimelinePortfolio from "./components/TimelinePortfolioComponent";
import * as timelineData from "./data.json";
import CONST from './util';
import "./style/App.css";

function App() {

    return ( 
        <div className="main-canvas">
            <div className="hero-container" style={{height: 300}}>
                <div className='site-title'>
                    <p className='terminal-line'>
                        ~/quinn/website $ <span>echo</span> $TITLE 
                    </p>
                    <h1>Quinn's Website</h1>
                </div>
                <div>
                    <p className='terminal-line'>
                        ~/quinn/website $ <span>echo</span> $DESCRIPTION 
                    </p>
                    <p>
                        Hello, nice to meet you! My name is Quinn Tao and I am a third year CS student at University of British Columbia, pursuing the dream of being a successful software engineer who built apps to benifite others. This website includes my work experience/ projects :D.   
                    </p>
                    <p className='terminal-line'>
                        ~/quinn/website $ <span>echotimeline</span> --list-work --list-project --list-volunteer
                    </p>
                </div>
            </div>
            <div className="portfolio-container">
                {initTimeline()}
            </div> 
            <div className="footer-container">
                <p className='terminal-line'>
                    ~/quinn/website $ <span>cd</span> ./contacts {'&&'} <span>ll</span>
                </p>
                <a href='https://github.com/t-quinn-t'>Github</a> <br></br>
                <a href='https://www.linkedin.com/in/qintu/'>LinkedIn</a>
                <p>Email: qintutao@gmail.com</p>
                <p>Cell: +1(604)813-0722</p>
                <p className='terminal-line'>
                    ~/quinn/website/contacts <span>echo</span> $AUTHOR
                </p>
                <p>Quinn Tao proudly built in 2021</p>
            </div>
        </div>
    );
}

/**
 * This function reads data.js and feeds data to timeline
 * @returns rendered timeline   
 */
function initTimeline() {

    const timelineTopTime       = CONST.timelineTopTime;
    const timelineBottomTime    = CONST.timelineBottomTime;

    let data = timelineData.raw;

    // Modify elements in data by appending additional properties
    //  "initdateDepth", "termdateDepth". These are pixel depth from top converted 
    //  from dates
    data.forEach(element => {
        let rawdate = element.termdate;
        if (rawdate === 'Present') {
            element['termdateDepth'] = 0;
        } else {
            let date = new Date(rawdate);
            let p = (CONST.timelineTopTime - date)/1000/60/60/24*CONST.DATE_TO_PIXEL_MULTIPLIER;
            element['termdateDepth'] = p;
        }
        rawdate = element.initdate;
        if (rawdate === 'Present') {
            element['initdateDepth'] = 0;
        }
        let date = new Date(rawdate);
        let p = (CONST.timelineTopTime - date)/1000/60/60/24*CONST.DATE_TO_PIXEL_MULTIPLIER;
        element['initdateDepth'] = p;
    })
    data.sort((c1, c2) => {
        return c1.termdateDepth - c2.termdateDepth
    })
    const timelineLength = (timelineTopTime - timelineBottomTime)/1000/60/60/24*CONST.DATE_TO_PIXEL_MULTIPLIER;
    return (
        <TimelinePortfolio 
            totalheight={timelineLength}
            data={data}
        />
    );
}

export default App;
